# Generated by Django 6.1.1 on 2026-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spend',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Over Budget', 'Over Budget')], max_length=20),
        ),
    ]
