# Generated by Django 6.1.1 on 2026-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0002_spend_department_alter_spend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='payment_method',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Purchase Order', 'Purchase Order'), ('Project', 'Project'), ('Annual Contract', 'Annual Contract'), ('Corporate Card', 'Corporate Card')], max_length=30),
        ),
    ]
